# This workflow will do a clean install of node dependencies, build the source code and run lint check

name: Run lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint
